version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test1234!         # MySQL root password
      MYSQL_DATABASE: recipe                  # The database you want to create (e.g., 'recipe')
    ports:
      - "3307:3306"                           # Exposing port 3306 to your machine
    networks:
      - app-network

  fastapi:
    build: .
    command: ["/app/wait-for-it.sh", "db:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
